package chromium

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/webong/ext/res/browser/extension"
)

// SignChromiumCRX asks the caller's Chrome-family executable to pack a CRX.
// A missing key is generated by the browser and saved next to the CRX; it must
// be kept by the caller for updates. This does not install the CRX.
func SignChromiumCRX(ctx context.Context, browser, executable, source, output, revision, keyPath string) (extension.BuildResult, error) {
	if !filepath.IsAbs(executable) {
		return extension.BuildResult{}, errors.New("browser executable must be an absolute path")
	}
	if info, err := os.Stat(executable); err != nil || !info.Mode().IsRegular() {
		return extension.BuildResult{}, fmt.Errorf("browser executable is unavailable: %s", executable)
	}
	description, err := extension.CheckedSource(source, revision)
	if err != nil {
		return extension.BuildResult{}, err
	}
	if err := extension.OutsideSource(source, output); err != nil {
		return extension.BuildResult{}, err
	}
	if err := extension.UnusedArtifact(output, ".crx"); err != nil {
		return extension.BuildResult{}, err
	}
	generatedKey := keyPath == ""
	if generatedKey {
		keyPath = strings.TrimSuffix(output, filepath.Ext(output)) + ".pem"
		if err := extension.OutsideSource(source, keyPath); err != nil {
			return extension.BuildResult{}, err
		}
		if err := extension.UnusedArtifact(keyPath, ".pem"); err != nil {
			return extension.BuildResult{}, err
		}
	} else {
		if !filepath.IsAbs(keyPath) {
			return extension.BuildResult{}, errors.New("existing key path must be absolute")
		}
		info, err := os.Lstat(keyPath)
		if err != nil || !info.Mode().IsRegular() {
			return extension.BuildResult{}, errors.New("existing key must be a regular file, not a symlink")
		}
	}
	if err := extension.OutsideSource(source, keyPath); err != nil {
		return extension.BuildResult{}, err
	}
	work, err := os.MkdirTemp("", "ctx-crx-")
	if err != nil {
		return extension.BuildResult{}, err
	}
	defer os.RemoveAll(work)
	staged := filepath.Join(work, "extension")
	if _, err := extension.StageWithRevision(source, staged, revision); err != nil {
		return extension.BuildResult{}, err
	}
	args := []string{"--no-first-run", "--no-default-browser-check", "--user-data-dir=" + filepath.Join(work, "browser-data"), "--pack-extension=" + staged}
	if !generatedKey {
		args = append(args, "--pack-extension-key="+keyPath)
	}
	if outputText, err := exec.CommandContext(ctx, executable, args...).CombinedOutput(); err != nil {
		return extension.BuildResult{}, fmt.Errorf("browser CRX packaging failed: %w: %s", err, strings.TrimSpace(string(outputText)))
	}
	crx := staged + ".crx"
	artifact, err := InspectCRX(crx)
	if err != nil {
		return extension.BuildResult{}, fmt.Errorf("browser did not produce a valid signed CRX3: %w", err)
	}
	if artifact.Version != description.Version {
		return extension.BuildResult{}, errors.New("packaged CRX version differs from reviewed source")
	}
	if current, err := extension.Inspect(source); err != nil || current.Revision != revision {
		return extension.BuildResult{}, errors.New("extension changed during CRX packaging")
	}
	if generatedKey {
		if err := extension.CopyArtifactExclusive(staged+".pem", keyPath, 0600); err != nil {
			return extension.BuildResult{}, fmt.Errorf("save generated private key: %w", err)
		}
	}
	if err := extension.CopyArtifactExclusive(crx, output, 0644); err != nil {
		if generatedKey {
			_ = os.Remove(keyPath)
		}
		return extension.BuildResult{}, err
	}
	artifactRevision, err := extension.FileSHA256(output)
	if err != nil || artifactRevision != artifact.Revision {
		_ = os.Remove(output)
		if generatedKey {
			_ = os.Remove(keyPath)
		}
		return extension.BuildResult{}, errors.New("CRX artifact changed while publishing the build output")
	}
	return extension.BuildResult{Status: "signed", Browser: browser, Source: output, SourceRevision: description.Revision,
		ArtifactRevision: artifactRevision, KeyPath: keyPath, ID: artifact.ID, Version: artifact.Version,
		NextAction: "Keep the private key private and reuse it for updates. Generate an update manifest for hosting, or register the CRX on a supported platform. Use the original source or ZIP with install for manual Load unpacked."}, nil
}
