#!/usr/bin/env bash
# Embed the shared page assets in the mobile hosts, so Swift and Java cannot drift
# from the one source of each:
#   pkg/plugin-wasm/page/reactor.js   the page-side reactor glue
#   res/web/bundle/shim.js            the web engine's page API shim
# Usage: scripts/plugin-mobile-assets.sh          write the generated files
#        scripts/plugin-mobile-assets.sh --check  fail if any is out of date
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - "${1:-}" <<'PY'
import sys

check = sys.argv[1] == '--check'
assets = {
    'reactorPage': 'pkg/plugin-wasm/page/reactor.js',
    'shim': 'res/web/bundle/shim.js',
}
sources = {name: open(path, encoding='utf-8').read() for name, path in assets.items()}
for name, text in sources.items():
    if '"""' in text or '"#' in text and '"""#' in text:
        raise SystemExit(f'{name}: contains a sequence the Swift raw string cannot hold')
    if len(text.encode('utf-8')) > 60000:
        raise SystemExit(f'{name}: too large for a single Java string constant')

HEADER = 'Generated by scripts/plugin-mobile-assets.sh from {}. Do not edit.'

def swift():
    out = ['// ' + HEADER.format(', '.join(assets.values())), '', 'enum GeneratedAssets {']
    for name, text in sources.items():
        out.append(f'    /// {assets[name]}')
        out.append(f'    static let {name} = ##"""')
        out.extend(text.rstrip('\n').split('\n'))
        out.append('"""##')
        out.append('')
    out[-1] = '}'
    return '\n'.join(out) + '\n'

def java_literal(text):
    lines = text.rstrip('\n').split('\n')
    parts = []
    for line in lines:
        escaped = line.replace('\\', '\\\\').replace('"', '\\"')
        parts.append('"' + escaped + '\\n"')
    return '\n            + '.join(parts)

def java():
    out = ['// ' + HEADER.format(', '.join(assets.values())),
           'package io.github.webong.ext.plugin.webview;', '',
           '/** The page assets the Android host embeds. */',
           'final class GeneratedAssets {',
           '    private GeneratedAssets() {}', '']
    for name, text in sources.items():
        out.append(f'    /** {assets[name]} */')
        out.append(f'    static final String {name.upper() if False else name} =\n            ' + java_literal(text) + ';')
        out.append('')
    out[-1] = '}'
    return '\n'.join(out) + '\n'

targets = {
    'pkg/plugin-ios/Sources/ExtPluginWebView/GeneratedAssets.swift': swift(),
    'pkg/plugin-android/src/android/java/io/github/webong/ext/plugin/webview/GeneratedAssets.java': java(),
}
stale = []
for path, content in targets.items():
    try:
        current = open(path, encoding='utf-8').read()
    except FileNotFoundError:
        current = None
    if current != content:
        stale.append(path)
        if not check:
            import os
            os.makedirs(os.path.dirname(path), exist_ok=True)
            open(path, 'w', encoding='utf-8').write(content)
if check and stale:
    raise SystemExit('out of date, run scripts/plugin-mobile-assets.sh: ' + ', '.join(stale))
print('up to date' if check else 'wrote ' + ', '.join(stale) if stale else 'already up to date')
PY
