#!/usr/bin/env bash
# Stage a release of the iOS plugin SDK. SwiftPM resolves a package from a repository
# root and this monorepo's root is not a package, so a release is two pieces:
#   1. CExtEngine.xcframework.zip, the engine's guest core for macOS, iOS and the
#      iOS Simulator, attached to a GitHub release of this repository, and
#   2. a distribution package (Package.swift plus the Swift sources) whose binary
#      target points at that archive by URL and checksum, to publish at a repository
#      root that SwiftPM can resolve.
# This script builds both under dist/plugin-ios-<version>/ and checks the distribution
# package compiles against the archive. It publishes nothing.
# Usage: scripts/plugin-ios-release.sh <version, for example 0.1.0>
set -euo pipefail
cd "$(dirname "$0")/.."
version="${1:?usage: scripts/plugin-ios-release.sh <version>}"
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo 'version must look like 0.1.0' >&2; exit 2; }
[[ "$(uname -s)" == Darwin ]] || { echo 'needs macOS and Xcode' >&2; exit 1; }
tag="plugin-ios-v$version"
repository="${EXT_REPOSITORY:-webong/ext}"
sdk=pkg/plugin-ios
out="dist/plugin-ios-$version"
rm -rf "$out"
mkdir -p "$out"

./scripts/plugin-mobile-assets.sh --check
./scripts/plugin-ios-xcframework.sh >/dev/null
( cd "$sdk/Frameworks" && ditto -c -k --sequesterRsrc --keepParent CExtEngine.xcframework "../../../$out/CExtEngine.xcframework.zip" )
checksum="$(swift package compute-checksum "$out/CExtEngine.xcframework.zip")"
url="https://github.com/$repository/releases/download/$tag/CExtEngine.xcframework.zip"

# The distribution package: the manifest with the binary target by URL and checksum.
dist="$out/package"
mkdir -p "$dist"
cp -R "$sdk/Sources" "$dist/Sources"
rm -rf "$dist/Sources/ExtConformancePlugin"
cp "$sdk/README.md" "$dist/README.md"
python3 - "$sdk/Package.swift" "$dist/Package.swift" "$url" "$checksum" <<'PY'
import re, sys
source, target, url, checksum = sys.argv[1:5]
text = open(source).read()
local = '.binaryTarget(name: "CExtEngine", path: "Frameworks/CExtEngine.xcframework")'
if local not in text:
    raise SystemExit('the development manifest no longer has the expected binary target')
text = text.replace(local, f'.binaryTarget(name: "CExtEngine", url: "{url}", checksum: "{checksum}")')
# Drop what only the repository's own tree can use: the tests, which read res/web and the
# engine, and the conformance fixture, which is not part of the SDK.
text = re.sub(r'\n\s*\.testTarget\([^\n]*\),', '', text)
text = re.sub(r'\n\s*// Test fixture for the cross-language conformance suite\.\n\s*\.library\(name: "ExtConformancePlugin"[^\n]*\n', '\n', text)
text = re.sub(r'\n\s*\.target\(name: "ExtConformancePlugin"[^\n]*\),', '', text)
text = re.sub(r'// Development manifest\..*?\n(?=let package)', '// Release manifest, generated by scripts/plugin-ios-release.sh. The binary target is the\n// published engine archive, pinned by checksum.\n', text, flags=re.S)
open(target, 'w').write(text)
PY

# Prove the staged package builds. The archive is on a release that does not exist
# yet, so build a copy whose binary target is the unzipped local xcframework.
verify="$(mktemp -d "${TMPDIR:-/tmp}/ext-ios-release.XXXXXX")"
trap 'rm -rf "$verify"' EXIT
cp -R "$dist/Sources" "$verify/Sources"
ditto -x -k "$out/CExtEngine.xcframework.zip" "$verify/Frameworks"
sed -E "s#\.binaryTarget\(name: \"CExtEngine\", url: \"[^\"]*\", checksum: \"[^\"]*\"\)#.binaryTarget(name: \"CExtEngine\", path: \"Frameworks/CExtEngine.xcframework\")#" "$dist/Package.swift" >"$verify/Package.swift"
swift build --package-path "$verify" >/dev/null

echo "version   $version"
echo "tag       $tag"
echo "archive   $out/CExtEngine.xcframework.zip"
echo "checksum  $checksum"
echo "url       $url"
echo "package   $dist (builds against the archive)"
